name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'Real-estate-frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www/realestate-project/Real-estate-frontend

            git pull origin master

            npm install

            npm run build