name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'Real-estate-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www/realestate-project/Real-estate-backend

            git pull origin master

            npm install

            pm2 restart backend-realestate

            pm2 save